variables:
  fontsize: 10pt
  linestretch: 1.15
  mainfont: "DejaVu Sans"
  monofont: "DejaVu Sans Mono"
  classoption: "letterpaper"
  geometry: "margin=0.75in"
  header-includes: |
    \usepackage{caption}
    \captionsetup[table]{font=small, labelfont=bf}
    \AtBeginEnvironment{tabular}{\small}
    \AtBeginEnvironment{longtable}{\small}
    \setlength{\tabcolsep}{4pt}
    \renewcommand{\arraystretch}{1.1}

toc: true
number-sections: true
